[package]
name = "xmodits-lib"
version = "0.3.0"
edition = "2021"
description = "XMODITS core library"
repository = "https://github.com/B0ney/xmodits-lib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.38"
bytemuck = "1.13.0"
rayon = "1.6.1"
fastrand = "1.8.0"
smol_str = "0.1.24"
extended = "0.1.0"
log = { version = "0.4.17", optional = false } # todo
serde = { version = "1.0.152", features = ["derive"] , optional = true }
ffmpeg-next = { version = "5.1.1", optional = true }

[dev-ddependencies]
env_logger = "0.10.0"

[features]
# logging = ["log"]
thread = []
serde_support = ["serde"]
ffmpeg = ["ffmpeg-next"]