[package]
name = "xmodits-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.38"
bytemuck = "1.13.0"
rayon = "1.6.1"
fastrand = "1.8.0"
log = "0.4.17"
smol_str = "0.1.24"
serde = { version = "1.0.152", features = ["derive"] , optional = true}

[dev-ddependencies]
env_logger = "0.10.0"

[features]
log = []
thread = []
serde_support = ["serde"]