[package]
name = "xmodits-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
byteorder = "1.4.3"
thiserror = "1.0.38"
phf = "0.11.1"
wav_io = "0.1"